FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait
WORKDIR /deps
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt
WORKDIR /app

RUN useradd --create-home --shell /bin/bash test && apt-get update && apt-get install -y postgresql
USER test

CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0 --port 5200
