FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
RUN apt-get update && \
    apt-get install -y postgresql postgresql-contrib
WORKDIR /deps
COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt
WORKDIR /app
RUN useradd --create-home --shell /bin/bash test && apt-get update && apt-get install -y postgresql
USER test
ENV DATABASE_URL="TEST"
ENV CORS_HOST="http://localhost:5300"
ENV SIGNING_KEY="sign"
ENV LOGGING="DEBUG"

CMD uvicorn main:app --reload --host 0.0.0.0 --port 5200
