name: Deploy Backend to heroku

on:
  push:
    branches:
      - main

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: login
          uses: actions/heroku@master
          env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        - name: set remote
          run: |
            git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
            git subtree push --prefix api heroku main
