name: Test and lint backend

on: push

permissions:
    contents: read

jobs:
    test-and-lint:
        if: github.ref != 'refs/heads/main'
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./api
        env:
            DATABASE_URL: ''
            CORS_HOST: '*'
            SIGNING_KEY: sign
            LOGGING: DEBUG
        steps:
        - uses: actions/checkout@v3
        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
            python-version: "3.10.11"
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install flake8
            pip install pytest
            pip install -r requirements.txt
            apt-get uppdate
            apt-get install -y postgresql postgresql-contrib
        - name: Lint with flake8
          run: |
            flake8 . --count --select=E9,F63,F7,F82 --show-source -statistics --exclude .venv
            flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude .venv
        - name: Test with pytest and testing.postgresql
          run: |
            python -m pytest tests
